### ISSUE TITLE
reference error

### ISSUE THREAD

**Issue by kgoedert** [tiberiuzuld/angular-auto-save-form#4]
Hi
I added the dependencies to my project and the attributes to the form. But when I load the page I get this error:

base.js:23068 ReferenceError: _ is not defined
    at saveFormLink (http://localhost:3010/app/js/base.js:68202:26)
    at invokeLinkFn (http://localhost:3010/app/js/base.js:19324:9)
    at nodeLinkFn (http://localhost:3010/app/js/base.js:18810:11)
    at compositeLinkFn (http://localhost:3010/app/js/base.js:18058:13)
    at compositeLinkFn (http://localhost:3010/app/js/base.js:18061:13)
    at nodeLinkFn (http://localhost:3010/app/js/base.js:18805:24)
    at compositeLinkFn (http://localhost:3010/app/js/base.js:18058:13)
    at publicLinkFn (http://localhost:3010/app/js/base.js:17938:30)
    at http://localhost:3010/app/js/base.js:50541:9
    at invokeLinkFn (http://localhost:3010/app/js/base.js:19324:9) <form form-wizard="" validate-form="" steps="4" name="projectForm" auto-save-form="projController.createProject" auto-save-form-debounce="500" class="ng-pristine ng-valid ng-scope" novalidate="">

What am I missing?

Thanks

**Comment by kgoedert** [comment]
I added the lodash dependency manually and now I get

base.js:23068 TypeError: _.debounce is not a function
    at saveFormLink (http://localhost:3010/app/js/base.js:72033:26)
    at invokeLinkFn (http://localhost:3010/app/js/base.js:19324:9)
    at nodeLinkFn (http://localhost:3010/app/js/base.js:18810:11)
    at compositeLinkFn (http://localhost:3010/app/js/base.js:18058:13)
    at compositeLinkFn (http://localhost:3010/app/js/base.js:18061:13)
    at publicLinkFn (http://localhost:3010/app/js/base.js:17938:30)
    at http://localhost:3010/app/js/base.js:50541:9
    at invokeLinkFn (http://localhost:3010/app/js/base.js:19324:9)
    at nodeLinkFn (http://localhost:3010/app/js/base.js:18810:11)
    at compositeLinkFn (http://localhost:3010/app/js/base.js:18058:13) <ng-form name="myForm" auto-save-form="c.save" class="ng-pristine ng-valid">

**Comment by kgoedert** [comment]
I updated the cache, lodash apparently loaded correctly. Now, when I type something in my form I get

Uncaught TypeError: saveFormCallback is not a function

My function is as follows

 vm.save = function(vars){
            console.log('no save');
            return $http.post("myfake", vars);
        };

**Comment by tiberiuzuld** [comment]
Hi,

Your html should be like

```
<form name="myForm" auto-save-form="controller.save" >
 <input ng-model="controller.user.firstName" name="firstName">
</form>

```

**Comment by kgoedert** [comment]
Hi,
it was my mistake. My controller wasn't created properly, so the function wasn't working as it should.
Thanks

**Comment by tiberiuzuld** [comment]
No problem.
